apiVersion: apps/v1
kind: Deployment
metadata:
  name: gke-edge-deployment
  labels:
    app: edge
  namespace: edge-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edge
  template:
    metadata:
      labels:
        app: edge
    spec:
      containers:
      - name: edge
        image: bandersaeed94/la79y:edge-v11
        command: ["node","--max-old-space-size=4096", "edge_docker_server_v2.js"]
        env:
        - name: SERVER_PORT
          value: "10081"
        - name: SERVER_ID
          value: "1"
        - name: KAFKA_BROKER_LIST
          value: "kafka-0.kafka-headless.kafka.svc.cluster.local:9092,kafka-1.kafka-headless.kafka.svc.cluster.local:9092,kafka-2.kafka-headless.kafka.svc.cluster.local:9092"
        - name: HEALTH_CHECK_PORT
          value: "9999"
        - name: DB_USER
          value: "admin"
        - name: DB_HOST
          value: "postgres.backend-namespace"
        - name: DB_DATABASE
          value: "la79y"
        - name: DB_PASSWORD
          value: "1234"
        - name: DB_PORT
          value: '5432'
        resources:
          requests:
            memory: "1024Mi"
            cpu: "1000m"
        ports:
        - containerPort: 10081
          protocol: UDP
        - containerPort: 9999
          protocol: TCP
        imagePullPolicy: Always
       

---
apiVersion: v1
kind: Service
metadata:
  name: edge-service-udp
  namespace: edge-namespace
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-port: "9999"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-check-interval-seconds: "60"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-response-timeout-seconds: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-unhealthy-threshold: "5"
    service.beta.kubernetes.io/do-loadbalancer-healthcheck-healthy-threshold: "1"
spec:
  type: LoadBalancer
  selector:
    app: edge
  ports:
  - name: edge-service-10081-10081
    port: 10081
    protocol: UDP
    targetPort: 10081
  - name: health-edge-service-9999-9999
    port: 9999
    protocol: TCP
    targetPort: 9999

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: edge-hpa
  namespace: edge-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gke-edge-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80  # Lowering this value to make the autoscaler more sensitive
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 60  # Lowering this value to make the autoscaler more sensitive
  behavior:
    scaleUp:
      policies:
        - type: Pods
          value: 2
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 1200
      policies:
        - type: Pods
          value: 1
          periodSeconds: 300
